# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\jocyn\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

print('Versão do numpy: ', np.__version__)

Versão do numpy:  1.22.3


# 1.3 Trabalhando com arrays Numpy

In [3]:
quilometragem_carro = np.loadtxt('data/carros-km.txt')
ano_carro = np.loadtxt('data/carros-anos.txt')

### Obtendo a quilometragem média por ano

In [4]:
quilometragem_media = quilometragem_carro / (2022 - ano_carro)

for i in quilometragem_carro:
    print("KM media:", i, end=' / ')

KM media: 44410.0 / KM media: 5712.0 / KM media: 37123.0 / KM media: 0.0 / KM media: 25757.0 / KM media: 10728.0 / KM media: 0.0 / KM media: 77599.0 / KM media: 99197.0 / KM media: 37978.0 / KM media: 12859.0 / KM media: 8052.0 / KM media: 89773.0 / KM media: 0.0 / KM media: 41457.0 / KM media: 115607.0 / KM media: 46449.0 / KM media: 0.0 / KM media: 37086.0 / KM media: 15173.0 / KM media: 101193.0 / KM media: 0.0 / KM media: 98079.0 / KM media: 102959.0 / KM media: 0.0 / KM media: 0.0 / KM media: 5795.0 / KM media: 0.0 / KM media: 58848.0 / KM media: 94381.0 / KM media: 30163.0 / KM media: 53332.0 / KM media: 17720.0 / KM media: 33808.0 / KM media: 90684.0 / KM media: 43975.0 / KM media: 0.0 / KM media: 0.0 / KM media: 5526.0 / KM media: 0.0 / KM media: 93415.0 / KM media: 40762.0 / KM media: 0.0 / KM media: 86302.0 / KM media: 0.0 / KM media: 9755.0 / KM media: 69945.0 / KM media: 2395.0 / KM media: 0.0 / KM media: 80349.0 / KM media: 85554.0 / KM media: 50496.0 / KM media: 67716.0 /

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [5]:
1+1

2

### Subtração ($-$)

In [6]:
5-2

3

### Multiplicação ($*$)

In [7]:
10*4

40

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [8]:
5/3

1.6666666666666667

In [9]:
5//3

1

### Exponenciação ($**$)

In [10]:
5**2

25

### Resto da divisão ($\%$)

In [11]:
5%2

1

In [12]:
6 % 2

0

### Expressões matemáticas

In [13]:
5*2 + 5*3

25

In [14]:
5*(2 + 5)*3

105

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [15]:
5*2

10

In [16]:
_ + 2

12

In [17]:
_ + 3

15

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variavel $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [18]:
numero = 10

numero += 10
print(numero)

numero -= 10
print(numero)

numero *= 10
print(numero)

numero /= 2
print(numero)

numero //= 2
print(numero)

numero %= 4
print(numero)

numero +=1
numero **= 8
print(numero)

20
10
100
50.0
25.0
1.0
256.0


# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [19]:
km_total = 44230
ano_atual = 2022
ano_fab = 2006

km_media = km_total / (ano_atual - ano_fab)
print('Quilometragem media do carro:', km_media)

Quilometragem media do carro: 2764.375


### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [20]:
km_total, ano_atual, ano_fab= 44230, 2022, 2006

print(km_total, ano_atual, ano_fab, sep=', ')

km_media = km_total / (ano_atual - ano_fab)
print('Quilometragem media do carro:', km_media)


44230, 2022, 2006
Quilometragem media do carro: 2764.375


# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [21]:
type(1)

int

In [22]:
type(1.1)

float

### Booleanos

In [23]:
type(1==1)

bool

In [24]:
type(1==2)

bool

In [25]:
type(True)

bool

In [26]:
type(False)

bool

### Strings

In [27]:
type('Ola')

str

In [28]:
type("Ola")

str

In [29]:
type(''' 
eu
sou
humano
''')

str

### None

In [30]:
type(None)

NoneType

# 2.4 Conversão de tipos

In [31]:
a = 10
b = 20
c = 'Olá, '
d = 'Mundo!'

In [32]:
a + b

30

In [33]:
c + d

'Olá, Mundo!'

In [34]:
c + d + str(10)

'Olá, Mundo!10'

In [35]:
numero = '10'
print(type(numero))
print(type(int(numero)))

<class 'str'>
<class 'int'>


In [36]:
numero = 10.42324234234324324
print(type(numero), numero)
print(type(int(numero)), int(numero))



<class 'float'> 10.423242342343244
<class 'int'> 10


In [37]:
numero = 10
print(type(numero), numero)
print(type(float(numero)), float(numero))

<class 'int'> 10
<class 'float'> 10.0


# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [38]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [39]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [40]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [41]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [42]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [43]:
print('%(nome)s é estudante de %(linguagem)s, há %(tempo)02d ano(s)' 
% {'nome': 'Jocy', 'linguagem': 'python', 'tempo': 2})

Jocy é estudante de python, há 02 ano(s)


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [44]:
nome, linguagem, tempo = 'Jocy', 'python',  2

print('{} é estudante de {} há {} ano(s)'.format(nome, linguagem, tempo))

Jocy é estudante de python há 2 ano(s)


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [45]:
nome, linguagem, tempo = 'Jocy', 'python',  2

print(f'{nome} é estudante de {linguagem} há {tempo} ano(s).')

Jocy é estudante de python há 2 ano(s).


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [46]:
acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### Lista com tipos de dados variados

In [47]:
carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [48]:
carros = [carro_1, carro_2]

In [49]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [50]:
acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [51]:
'rodas de liga' in acessorios

False

In [52]:
'rodas de liga'.capitalize() in acessorios

True

In [53]:
'parachoque dianteiro'.capitalize() not in acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [54]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [55]:
C = A + B
C

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [56]:
tamanho_lista = len(C)
print(f'A lista possui tamanho de {tamanho_lista} iten(s)')

A lista possui tamanho de 8 iten(s)


# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [67]:
carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]
carros = [carro_1, carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [71]:
carro_1[1]

'Motor 4.0 Turbo'

In [72]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [73]:
carros[0][1]

'Motor 4.0 Turbo'

In [75]:
carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [76]:
carros[0][-2][0]

'Rodas de liga'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [78]:
acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [81]:
acessorios[3:6]

['Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento']

In [82]:
acessorios[3:]

['Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [83]:
acessorios[:6]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [84]:
acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [86]:
acessorios.sort()
acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [87]:
acessorios.append('Freio ABS')
acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Freio ABS']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [88]:
acessorios.pop()
acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [89]:
acessorios.pop(1)

'Bancos de couro'

In [90]:
acessorios

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

**# PRIMEIRO METODO**

In [91]:
acessorios_2 = acessorios.copy()
acessorios_2

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [93]:
acessorios_2.pop()
acessorios_2

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva']

In [94]:
acessorios

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

**# SEGUNDO METODO**

In [95]:
acessorios_3 = acessorios[:]
acessorios_3

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [96]:
acessorios_3.append('Freio ABS')
acessorios_3

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Freio ABS']

In [97]:
acessorios

['Ar condicionado',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [2]:
acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [4]:
for item in acessorios:
    print(item, end=', ')

Rodas de liga, Travas elétricas, Piloto automático, Bancos de couro, Ar condicionado, Sensor de estacionamento, Sensor crepuscular, Sensor de chuva, 

###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [5]:
range(10)

range(0, 10)

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
for i in range(10):
    print(i ** 2, end=', ')

0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 

In [9]:
lista = []

for i in range(10):
    lista.append(i ** 2)

print(lista)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [11]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [12]:
for lista in dados:
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [13]:
for lista in dados:
    for item in lista:
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [14]:
acessorios = []

for lista in dados:
    for item in lista:
        acessorios.append(item)

print(acessorios)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [15]:
set(acessorios)

{'4 X 4',
 'Ar condicionado',
 'Bancos de couro',
 'Central multimídia',
 'Controle de estabilidade',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Freios ABS',
 'Painel digital',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Travas elétricas',
 'Vidros elétricos'}

In [16]:
list(set(acessorios))

['Ar condicionado',
 'Freios ABS',
 'Painel digital',
 'Sensor de estacionamento',
 '4 X 4',
 'Câmera de estacionamento',
 'Piloto automático',
 'Rodas de liga',
 'Controle de estabilidade',
 'Bancos de couro',
 'Sensor crepuscular',
 'Teto panorâmico',
 'Câmbio automático',
 'Central multimídia',
 'Vidros elétricos',
 'Sensor de chuva',
 'Travas elétricas']

### List comprehensions

In [ ]:
'''
acessorios = []

for lista in dados:
    for item in lista:
        acessorios.append(item)

print(acessorios)
'''

In [18]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [20]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [22]:
for lista in dados:
    if(lista[2] == True):
        print(lista)

['DS5', 2019, True]
['A5', 2019, True]


In [28]:
carro_0km = []

for lista in dados:
    if(lista[2] == True):
        carro_0km.append(lista)

carro_0km

[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [30]:
[lista for lista in dados if(lista[2] == True)]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [59]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [60]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [1]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [2]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [3]:
import numpy as np

In [4]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Importando parte do pacote

In [5]:
from numpy import arange

In [6]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [8]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [15]:
km = np.array([0, 12312, 1232, 20, 23435])
km

array([    0, 12312,  1232,    20, 23435])

In [16]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [17]:
km.dtype

dtype('int32')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [25]:
km_carros = np.loadtxt('data/carros-km.txt', dtype = 'int')
km_carros

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [26]:
km_carros.dtype

dtype('int32')

### Arrays com duas dimensões

In [27]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [30]:
acessorios = np.array(dados)
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [31]:
acessorios.dtype

dtype('<U24')

In [32]:
acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [43]:
array_np = np.arange(10000)

In [44]:
lista_py = list(range(10000))

In [45]:
%time for _ in array_np: array_np *= 2

CPU times: total: 156 ms
Wall time: 242 ms


In [46]:
%time for _ in lista_py: lista_py = [i * 2 for i in lista_py]

CPU times: total: 1min 41s
Wall time: 1min 57s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [49]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

### Operações entre arrays

In [54]:
idade = 2022 - anos
idade

array([19, 31, 32,  3, 16])

In [55]:
km_medio = km / idade
km_medio

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

### Operações com arrays de duas dimensões

In [57]:
matriz_np = np.array([km, anos])
matriz_np

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [61]:
matriz_np.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [59]:
km_matriz = matriz_np[0]
km_matriz

array([44410.,  5712., 37123.,     0., 25757.])

In [60]:
anos_matriz = matriz_np[1]
anos_matriz

array([2003., 1991., 1990., 2019., 2006.])

In [62]:
km_medio = km_matriz / (2022 - anos_matriz)
km_medio

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [67]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [73]:
matriz = np.array([km, anos])
matriz

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [68]:
array[2]

2

In [69]:
array[-2]

8

In [71]:
array[4:8]

array([4, 5, 6, 7])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [74]:
matriz[1][1]

1991.0

In [75]:
matriz[1, 1]

1991.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [77]:
matriz[:]

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [80]:
matriz[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [81]:
matriz[:1, 1:4]

array([[ 5712., 37123.,     0.]])

In [82]:
matriz[1:, 1:4]

array([[1991., 1990., 2019.]])

In [84]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
array[2::2]

array([2, 4, 6, 8])

In [87]:
array[1::3]

array([1, 4, 7])

In [88]:
array[::2]

array([0, 2, 4, 6, 8])

In [89]:
array[1:6:3]

array([1, 4])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [90]:
matriz

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [91]:
matriz[1] > 2000

array([ True, False, False,  True,  True])

In [93]:
matriz[:,matriz[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [94]:
matriz[1, [True, False, False,  True,  True]]

array([2003., 2019., 2006.])

In [98]:
matriz[:, matriz[1] > 2000][1]

array([2003., 2019., 2006.])

In [99]:
matriz[1:, matriz[1] > 2000]

array([[2003., 2019., 2006.]])

In [102]:
km_media = matriz[:1, matriz[1] > 2000] / (2022 - matriz[1:, matriz[1] > 2000])
km_media

array([[2337.36842105,    0.        , 1609.8125    ]])

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

## *ndarray.ndim*

Retorna o número de dimensões do array.

## *ndarray.size*

Retorna o número de elementos do array.

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [21]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [22]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

FileNotFoundError: carros-anos.txt not found.

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.